### ISSUE TITLE
Malformed HTTP/1.1 Requests

### ISSUE THREAD

**Issue by penn5** [pyos/libcno#2]
CNO is sending
```
192.168.001.122.37058-040.112.064.018.00080: POST /common/oauth2/v2.0/token HTTP/1.1

192.168.001.122.37058-040.112.064.018.00080: host: login.microsoftonline.com

192.168.001.122.37058-040.112.064.018.00080: User-Agent: python-cno/1.0
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip, deflate
Connection: keep-alive
Accept: */*
Content-Length: 886
transfer-encoding: chunked
connection: keep-alive

376
<the_form_data>
192.168.001.122.37058-040.112.064.018.00080: 

192.168.001.122.37058-040.112.064.018.00080: 0

```
(the output from tcpflow)

This should look like

```
192.168.001.122.33628-040.112.064.025.00080: POST /common/oauth2/v2.0/token HTTP/1.1
Host: login.microsoftonline.com
Accept: */*
Accept-Encoding: gzip, deflate
User-Agent: python-requests/2.18.4
Connection: keep-alive
Content-Length: 993
Content-Type: application/x-www-form-urlencoded


192.168.001.122.33628-040.112.064.025.00080: <the_form_data>

```
(the output from tcpflow on the same request from python-requests)

Note that I manually requested the user-agent header in the first one, that is not representative of the version installed. I have installed, using the install instructions, since the last commit was made to github.

GET requests look very similar

**Comment by pyos** [comment]
`content-length` is expected to be in lower case (http 2 does not allow uppercase characters in headers; http 1 doesn't care), which is why the library does not detect it and tries to use chunked `transfer-encoding` (same for `Connection` vs `connection`).

I've added automatic case conversion to Python bindings in fa78a98. Not sure what to do about C, as case-converting possibly constant strings requires allocating dynamic buffers, and I'd rather avoid that.

**Comment by penn5** [comment]
The problem is not with the headers, but with the number of separate transmissions.

For example, cno is sending the Host header on a separate transmission; whereas python-requests is sending both the headers and request all on one transmission. 

From your above comment, I'm wondering if the problem is that it's passing the headers as chunked.

**Comment by pyos** [comment]
The number of transmissions shouldn't matter, as the whole protocol works on top of a streaming connection that may regroup data arbitrarily.

That said, you can always buffer the data passed to on_write yourself if you have the dynamically allocated memory to spare.

**Comment by pyos** [comment]
That doesn't make the request malformed. Data sent over a streamed connection does not need to be grouped in any particular way, unlike datagram-based connections.

(It *may* be suboptimal, though. I'll try forcing some buffering in the Python bindings.)

**Comment by penn5** [comment]
I know nothing of the standard, but the only difference is the grouping (vs requests), and the Microsoft server is rejecting the request. Is this streamed format new in http/2.0? The MS servers don't support 2.0.

**Comment by pyos** [comment]
There's another difference which I already mentioned (chunked transfer-encoding, which is invalid when content-length is present, which it is). That one should be fixed already. Does the server still reject the request after updating the library?

**Comment by pyos** [comment]
Closing this because the C library will now reject lowercase headers with an error, while Python bindings convert case automatically. I see no other problems with the request.
