### ISSUE TITLE
h2-upgrade sequence becomes out of order?

### ISSUE THREAD

**Issue by yarf** [pyos/libcno#3]
Hello;

Using libcno as a server, with test clients nghttp and curl. All operates as expected apart from where either client initiates an h2-upgrade scenario (and CNO_SERVER instances are configured with cno_connection_made<CNO_HTTP1>).

Once a client connection is established, the server-side goes through CNO_CONNECTION_STATE 4 and 5  and issues the onStreamStart and onMessageStart for stream #1 as expected. As a result of onMessageStart, the server invokes cno_write_message() followed by cno_write_data() with the "end" flag set true.

**Comment by yarf** [comment]
(submitted early)

**Comment by yarf** [comment]
(submitted early)

Under those circumstances we get into a scenario whereby onStreamEnd is issued before onMessageEnd; we're now at CNO_CONNECTION_STATE 7 and when cno_connection_proceed iterates once more, after unwinding from the original onMessageSend, it finds itself without a valid stream instance here
```
        case CNO_CONNECTION_HTTP1_READING:
        case CNO_CONNECTION_HTTP1_READING_UPGRADE: {
            struct cno_stream_t *stream = cno_stream_find(conn, 1);

```
and segfaults on the resultant dereference when attempting to issue the (now out of order) onMessageEnd.

**Comment by pyos** [comment]
Upgrading to h2c while writing a response without reading the request's body should work fine now, thanks for the report!

**Comment by yarf** [comment]
you are welcome! Thank you :)
